<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pits_site_statistics"
 *
 * Auto generated by Extension Builder 2016-04-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Site Statistics',
	'description' => 'An extension uses Google analytics data to plot the Website analytics graphically.',
	'category' => 'module',
	'author' => 'Ricky Mathew',
	'author_email' => 'ricky.mk@pitsolutions.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);